# Welcome to Jekyll!

# Website settings
title: "Think Smarter, Code Smarter"
description: "Peng's blog, share thoughts on javascript, android and iOS development experience"
keywords: "Peng,javascript, angular,rxjs,android,ios,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://gogeek.me"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Peng'
  first_name: 'Peng'
  last_name: 'Wang'
  email: 'wpcfan@gmail.com'
  facebook_username: 'peng.wang'
  github_username: 'wpcfan'
  head_img: 'static/img/landing/profile.jpg'
  desc: 'I am a Full Stack engineer and the co-founder of Soulkey Tech Ltd. Life is a continuous learning process, and sharing my thoughts while I am learning may benefit both of us'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://gogeek.me/static/img/blog'

# donate
donate:
  wechat1: 'static/img/pay/w1.jpeg'
  wechat5: 'static/img/pay/w5.jpeg'

# comment
changyan:
   appid: cysKvjNmC
   conf: 14195e6733a549bb2f800fb931489c56
# disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 59fd3d05-03d3-43ad-9650-ef46f9487bb8

# baidu analytics
ba:
  uuid: fc44e98b7062976fd7982188c4179bb8

# google analytics
# ga:
  # id: UA-73784599-1

# growingIO
# gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
